// THIS FILE IS AUTO-GENERATED, PLEASE DO NOT MODIFY!

#if !defined( GENERATED_DEFINES_H )
#define GENERATED_DEFINES_H

#define PALETTE_COLORS 42
#define TILE_MAX_ENEMY_INDEX_POOL_ENEMIES 5
#define TILE_OVERWORLD_ENEMY_INDEX_POOLS 14
#define TILE_DUNGEON_ENEMY_INDEX_POOLS 7
#define ACTIVE_SPRITE_PLAYER_ID 0
#define ACTIVE_SPRITE_PLAYER_CARRY_ID 10
#define THRONE_ROOM_PRINCESS_NPC_ID 1

#endif // GENERATED_DEFINES_H
