#if !defined( STRINGS_H )
#define STRINGS_H

#define STRING_OVERWORLD_MENU_TITLE                   "COMMAND"
#define STRING_OVERWORLD_MENU_TALK                    "TALK"
#define STRING_OVERWORLD_MENU_STATUS                  "STATUS"
#define STRING_OVERWORLD_MENU_SEARCH                  "SEARCH"
#define STRING_OVERWORLD_MENU_SPELL                   "SPELL"
#define STRING_OVERWORLD_MENU_ITEM                    "ITEM"
#define STRING_OVERWORLD_MENU_DOOR                    "DOOR"

#define STRING_OVERWORLD_ITEMMENU_HERB                "Herb    %u"
#define STRING_OVERWORLD_ITEMMENU_WING                "Wing    %u"
#define STRING_OVERWORLD_ITEMMENU_FAIRYWATER_1        "Fairy   %u"
#define STRING_OVERWORLD_ITEMMENU_FAIRYWATER_2        " Water"
#define STRING_OVERWORLD_ITEMMENU_SILVERHARP_1        "Silver"
#define STRING_OVERWORLD_ITEMMENU_SILVERHARP_2        " Harp"
#define STRING_OVERWORLD_ITEMMENU_FAIRYFLUTE_1        "Fairy"
#define STRING_OVERWORLD_ITEMMENU_FAIRYFLUTE_2        " Flute"
#define STRING_OVERWORLD_ITEMMENU_GWAELYNSLOVE_1      "Gwaelyn's"
#define STRING_OVERWORLD_ITEMMENU_GWAELYNSLOVE_2      " Love"
#define STRING_OVERWORLD_ITEMMENU_RAINBOWDROP_1       "Rainbow"
#define STRING_OVERWORLD_ITEMMENU_RAINBOWDROP_2       " Drop"
#define STRING_OVERWORLD_ITEMMENU_KEY                 "Key     %u"
#define STRING_OVERWORLD_ITEMMENU_TOKEN_1             "Erdrick's"
#define STRING_OVERWORLD_ITEMMENU_TOKEN_2             " Token"
#define STRING_OVERWORLD_ITEMMENU_STONEOFSUNLIGHT_1   "Stone of"
#define STRING_OVERWORLD_ITEMMENU_STONEOFSUNLIGHT_2   " Sunlight"
#define STRING_OVERWORLD_ITEMMENU_STAFFOFRAIN_1       "Staff of"
#define STRING_OVERWORLD_ITEMMENU_STAFFOFRAIN_2       " Rain"
#define STRING_OVERWORLD_ITEMMENU_SPHEREOFLIGHT_1     "Sphere of"
#define STRING_OVERWORLD_ITEMMENU_SPHEREOFLIGHT_2     " Light"

#define STRING_OVERWORLD_QUICKSTATS_LEVEL             "LV"
#define STRING_OVERWORLD_QUICKSTATS_HP                "HP"
#define STRING_OVERWORLD_QUICKSTATS_MP                "MP"
#define STRING_OVERWORLD_QUICKSTATS_GOLD              "G"
#define STRING_OVERWORLD_QUICKSTATS_EXP               "E"

#define STRING_OVERWORLD_DEEPSTATS_NAME               "NAME: %s"
#define STRING_OVERWORLD_DEEPSTATS_STRENGTH           "STRENGTH: %u"
#define STRING_OVERWORLD_DEEPSTATS_AGILITY            "AGILITY: %u"
#define STRING_OVERWORLD_DEEPSTATS_MAXHP              "MAX HP: %u"
#define STRING_OVERWORLD_DEEPSTATS_MAXMP              "MAX MP: %u"
#define STRING_OVERWORLD_DEEPSTATS_ATTACK             "ATTACK: %u"
#define STRING_OVERWORLD_DEEPSTATS_DEFENSE            "DEFENSE: %u"
#define STRING_OVERWORLD_DEEPSTATS_WEAPON             "WEAPON: %s"
#define STRING_OVERWORLD_DEEPSTATS_ARMOR              "ARMOR: %s"
#define STRING_OVERWORLD_DEEPSTATS_SHIELD             "SHIELD: %s"
#define STRING_OVERWORLD_DEEPSTATS_NONE               "(none)"

#define STRING_OVERWORLD_DIALOG_NOBODY_THERE          "Nobody is there."
#define STRING_OVERWORLD_DIALOG_SEARCH                "%s searched the ground all about."
#define STRING_OVERWORLD_DIALOG_SEARCH_NOT_FOUND      "But there found nothing."
#define STRING_OVERWORLD_DIALOG_NO_SPELLS             "You do not know any spells."
#define STRING_OVERWORLD_DIALOG_NO_ITEMS              "You do not have any items."
#define STRING_OVERWORLD_DIALOG_NO_DOOR               "There is no door here."

#endif // STRINGS_H
