#if !defined( STRINGS_H )
#define STRINGS_H

#define STRING_INDEFINITE_ARTICLE_A                                  "A"
#define STRING_INDEFINITE_ARTICLE_AN                                 "An"
#define STRING_POINT                                                 "point"
#define STRING_POINTS                                                "points"
#define STRING_YES                                                   "YES"
#define STRING_NO                                                    "NO"
#define STRING_BUY                                                   "BUY"
#define STRING_SELL                                                  "SELL"

#define STRING_STARTUP_MENU_START                                    "Venture Forth!"
#define STRING_STARTUP_MENU_PASSWORD                                 "Enter Password"
#define STRING_STARTUP_MENU_CONTINUE                                 "Load From Save"
#define STRING_ALPHAPICKER_NAME_TITLE                                "NAME"
#define STRING_ALPHAPICKER_PASSWORD_TITLE                            "PASSWORD"
#define STRING_ALPHAPICKER_NAME_END                                  "END"

#define STRING_OVERWORLD_MENU_TITLE                                  "COMMAND"
#define STRING_OVERWORLD_MENU_TALK                                   "TALK"
#define STRING_OVERWORLD_MENU_STATUS                                 "STATUS"
#define STRING_OVERWORLD_MENU_SEARCH                                 "SEARCH"
#define STRING_OVERWORLD_MENU_SPELL                                  "SPELL"
#define STRING_OVERWORLD_MENU_ITEM                                   "ITEM"
#define STRING_OVERWORLD_MENU_DOOR                                   "DOOR"

#define STRING_SPELL_HEAL                                            "Heal"
#define STRING_SPELL_SIZZ                                            "Sizz"
#define STRING_SPELL_SLEEP                                           "Sleep"
#define STRING_SPELL_GLOW                                            "Glow"
#define STRING_SPELL_FIZZLE                                          "Fizzle"
#define STRING_SPELL_EVAC                                            "Evac"
#define STRING_SPELL_ZOOM                                            "Zoom"
#define STRING_SPELL_REPEL                                           "Repel"
#define STRING_SPELL_MIDHEAL                                         "Cure"
#define STRING_SPELL_SIZZLE                                          "Sizzle"

#define STRING_ACCESSORY_NONE                                        "(none)"

#define STRING_WEAPON_BAMBOOPOLE1                                    "Bamboo"
#define STRING_WEAPON_BAMBOOPOLE2                                    "Pole"
#define STRING_WEAPON_CLUB                                           "Club"
#define STRING_WEAPON_COPPERSWORD1                                   "Copper"
#define STRING_WEAPON_COPPERSWORD2                                   "Sword"
#define STRING_WEAPON_HANDAXE                                        "Hand Axe"
#define STRING_WEAPON_BROADSWORD1                                    "Broad"
#define STRING_WEAPON_BROADSWORD2                                    "Sword"
#define STRING_WEAPON_FLAMESWORD1                                    "Flame"
#define STRING_WEAPON_FLAMESWORD2                                    "Sword"
#define STRING_WEAPON_ERDRICKSSWORD1                                 "Erdrick's"
#define STRING_WEAPON_ERDRICKSSWORD2                                 "Sword"

#define STRING_ITEM_KEY                                              "Key"
#define STRING_ITEM_HERB                                             "Herb"
#define STRING_ITEM_WING                                             "Wing"
#define STRING_ITEM_FAIRYWATER1                                      "Fairy"
#define STRING_ITEM_FAIRYWATER2                                      "Water"
#define STRING_ITEM_TORCH                                            "Torch"
#define STRING_ITEM_DRAGONSCALE1                                     "Dragon"
#define STRING_ITEM_DRAGONSCALE2                                     "Scale"

#define STRING_ITEM_SELLKEY                                          "key"
#define STRING_ITEM_SELLHERB                                         "herb"
#define STRING_ITEM_SELLWING                                         "wing"
#define STRING_ITEM_SELLTORCH                                        "torch"
#define STRING_ITEM_SELLFAIRYWATER                                   "Fairy Water"
#define STRING_ITEM_SELLDRAGONSCALE                                  "Dragon's Scale"

#define STRING_WEAPON_SELLBAMBOOPOLE                                 "Bamboo Pole"
#define STRING_WEAPON_SELLCLUB                                       "Club"
#define STRING_WEAPON_SELLCOPPERSWORD                                "Copper Sword"
#define STRING_WEAPON_SELLHANDAXE                                    "Hand Axe"
#define STRING_WEAPON_SELLBROADSWORD                                 "Broad Sword"
#define STRING_WEAPON_SELLFLAMESWORD                                 "Flame Sword"

#define STRING_ARMOR_CLOTHES                                         "Clothes"
#define STRING_ARMOR_LEATHERARMOR1                                   "Leather"
#define STRING_ARMOR_LEATHERARMOR2                                   "Armor"
#define STRING_ARMOR_CHAINMAIL1                                      "Chain"
#define STRING_ARMOR_CHAINMAIL2                                      "Mail"
#define STRING_ARMOR_HALFPLATE1                                      "Half"
#define STRING_ARMOR_HALFPLATE2                                      "Plate"
#define STRING_ARMOR_FULLPLATE1                                      "Full"
#define STRING_ARMOR_FULLPLATE2                                      "Plate"
#define STRING_ARMOR_MAGICARMOR1                                     "Magic"
#define STRING_ARMOR_MAGICARMOR2                                     "Armor"
#define STRING_ARMOR_ERDRICKSARMOR1                                  "Erdrick's"
#define STRING_ARMOR_ERDRICKSARMOR2                                  "Armor"

#define STRING_ARMOR_SELLCLOTHES                                     "Clothes"
#define STRING_ARMOR_SELLLEATHERARMOR                                "Leather Armor"
#define STRING_ARMOR_SELLCHAINMAIL                                   "Chain Mail"
#define STRING_ARMOR_SELLHALFPLATE                                   "Half Plate"
#define STRING_ARMOR_SELLFULLPLATE                                   "Full Plate"
#define STRING_ARMOR_SELLMAGICARMOR                                  "Magic Armor"

#define STRING_SHIELD_SMALL1                                         "Small"
#define STRING_SHIELD_SMALL2                                         "Shield"
#define STRING_SHIELD_LARGE1                                         "Large"
#define STRING_SHIELD_LARGE2                                         "Shield"
#define STRING_SHIELD_SILVER1                                        "Silver"
#define STRING_SHIELD_SILVER2                                        "Shield"

#define STRING_SHIELD_SELLSMALL                                      "Small Shield"
#define STRING_SHIELD_SELLLARGE                                      "Large Shield"
#define STRING_SHIELD_SELLSILVER                                     "Silver Shield"

#define STRING_TOWN_TANTEGEL                                         "Tantegel"
#define STRING_TOWN_BRECCONARY                                       "Brecconary"
#define STRING_TOWN_GARINHAM                                         "Garinham"
#define STRING_TOWN_KOL                                              "Kol"
#define STRING_TOWN_RIMULDAR                                         "Rimuldar"
#define STRING_TOWN_CANTLIN                                          "Cantlin"

#define STRING_OVERWORLD_ITEMMENU_KEY                                "Key     %u"
#define STRING_OVERWORLD_ITEMMENU_HERB                               "Herb    %u"
#define STRING_OVERWORLD_ITEMMENU_WING                               "Wing    %u"
#define STRING_OVERWORLD_ITEMMENU_FAIRYWATER_1                       "Fairy   %u"
#define STRING_OVERWORLD_ITEMMENU_FAIRYWATER_2                       " Water"
#define STRING_OVERWORLD_ITEMMENU_TORCH                              "Torch   %u"
#define STRING_OVERWORLD_ITEMMENU_FAIRYFLUTE_1                       "Fairy"
#define STRING_OVERWORLD_ITEMMENU_FAIRYFLUTE_2                       " Flute"
#define STRING_OVERWORLD_ITEMMENU_SILVERHARP_1                       "Silver"
#define STRING_OVERWORLD_ITEMMENU_SILVERHARP_2                       " Harp"
#define STRING_OVERWORLD_ITEMMENU_GWAELINSLOVE_1                     "Gwaelin's"
#define STRING_OVERWORLD_ITEMMENU_GWAELINSLOVE_2                     " Love"
#define STRING_OVERWORLD_ITEMMENU_STONEOFSUNLIGHT_1                  "Stone of"
#define STRING_OVERWORLD_ITEMMENU_STONEOFSUNLIGHT_2                  " Sunlight"
#define STRING_OVERWORLD_ITEMMENU_STAFFOFRAIN_1                      "Staff of"
#define STRING_OVERWORLD_ITEMMENU_STAFFOFRAIN_2                      " Rain"
#define STRING_OVERWORLD_ITEMMENU_TOKEN_1                            "Erdrick's"
#define STRING_OVERWORLD_ITEMMENU_TOKEN_2                            " Token"
#define STRING_OVERWORLD_ITEMMENU_RAINBOWDROP_1                      "Rainbow"
#define STRING_OVERWORLD_ITEMMENU_RAINBOWDROP_2                      " Drop"
#define STRING_OVERWORLD_ITEMMENU_SPHEREOFLIGHT_1                    "Sphere of"
#define STRING_OVERWORLD_ITEMMENU_SPHEREOFLIGHT_2                    " Light"
#define STRING_OVERWORLD_ITEMMENU_DRAGONSCALE_1                      "Dragon's"
#define STRING_OVERWORLD_ITEMMENU_DRAGONSCALE_2                      " Scale"
#define STRING_OVERWORLD_ITEMMENU_CURSEDBELT_1                       "Cursed"
#define STRING_OVERWORLD_ITEMMENU_CURSEDBELT_2                       " Belt"

#define STRING_QUICKSTATS_LEVEL                                      "LV"
#define STRING_QUICKSTATS_HP                                         "HP"
#define STRING_QUICKSTATS_MP                                         "MP"
#define STRING_QUICKSTATS_GOLD                                       "G"
#define STRING_QUICKSTATS_EXP                                        "E"

#define STRING_OVERWORLD_DEEPSTATS_NAME                              "NAME: %s"
#define STRING_OVERWORLD_DEEPSTATS_STRENGTH                          "STRENGTH: %u"
#define STRING_OVERWORLD_DEEPSTATS_AGILITY                           "AGILITY: %u"
#define STRING_OVERWORLD_DEEPSTATS_MAXHP                             "MAX HP: %u"
#define STRING_OVERWORLD_DEEPSTATS_MAXMP                             "MAX MP: %u"
#define STRING_OVERWORLD_DEEPSTATS_ATTACK                            "ATTACK: %u"
#define STRING_OVERWORLD_DEEPSTATS_DEFENSE                           "DEFENSE: %u"
#define STRING_OVERWORLD_DEEPSTATS_WEAPON                            "WEAPON:"
#define STRING_OVERWORLD_DEEPSTATS_ARMOR                             "ARMOR:"
#define STRING_OVERWORLD_DEEPSTATS_SHIELD                            "SHIELD:"
#define STRING_OVERWORLD_DEEPSTATS_SPELLS                            "SPELLS"

#define STRING_DIALOG_NOBODY_THERE                                   "Nobody is there."
#define STRING_DIALOG_SEARCH                                         "You search the ground all about."
#define STRING_DIALOG_SEARCH_NOT_FOUND                               "But there is nothing to be found."
#define STRING_DIALOG_SEARCH_FOUND                                   "You find %s!"
#define STRING_DIALOG_NO_SPELLS                                      "You do not know any spells."
#define STRING_DIALOG_SPELLS_OVERWORLD_CANT_CAST                     "You do not know any spells that can be cast here."
#define STRING_DIALOG_SPELLS_OVERWORLD_CAST                          "You cast %s."
#define STRING_DIALOG_SPELLS_GLOW_SPHEREOFLIGHT                      "The Sphere of Light burns brighter than any spell could accomplish!"
#define STRING_DIALOG_HEAL_RESULT                                    "You have recovered %u hit %s."
#define STRING_DIALOG_NO_ITEMS                                       "You do not have any items."
#define STRING_DIALOG_NO_DOOR                                        "There is no door here."
#define STRING_DIALOG_NO_KEYS                                        "You do not have any keys."
#define STRING_DIALOG_DRAGONLORDTHRONE                               "You feel a light breeze flowing from behind the Dragonlord's throne..."
#define STRING_DIALOG_FOUNDSPHEREOFLIGHT_1                           "You have found the Sphere of Light!"
#define STRING_DIALOG_FOUNDSPHEREOFLIGHT_2                           "As you hold it aloft, its radiance streams forth."
#define STRING_DIALOG_FOUNDSPHEREOFLIGHT_3                           "The darkness and shadows hide from its brilliance, as do the Dragonlord's minions!"
#define STRING_DIALOG_DEAD                                           "You fall to the ground, lifeless..."
#define STRING_DIALOG_EXPEL_1                                        "\"You there, hey! Stop!\""
#define STRING_DIALOG_EXPEL_2                                        "\"This is a place of purity, we cannot allow a curse to befall our people!\""
#define STRING_DIALOG_EXPEL_3                                        "\"Guards, let's remove this individual from the premises!\""
#define STRING_DIALOG_CURSEDBELT_TANTEGEL_1                          "You wrap the cursed belt around your waist..."
#define STRING_DIALOG_CURSEDBELT_TANTEGEL_2                          "Yet you can't bring yourself to buckle it, a mysterious benevolent force stops you."

#define STRING_HOLYPROTECTION_ON                                     "A barrier of Holy Protection surrounds you."
#define STRING_HOLYPROTECTION_OFF                                    "The effects of Holy Protection have worn off."
#define STRING_HOLYPROTECTION_CURSED                                 "But the curse dispels the Holy Protection."
#define STRING_GLOW_CURSED                                           "But the curse draws the darkness back to you."
#define STRING_EVAC_CURSED                                           "But the curse restrains you from the outside light."

#define STRING_BUTNOTHINGHAPPENS                                     "But nothing happens."
#define STRING_NOTENOUGHMP                                           "You do not have enough MP."
#define STRING_SPELLBLOCKED                                          "But a mysterious force has contained your magic!"
#define STRING_FULLYHEALED                                           "You are already fully healed."
#define STRING_CURSED                                                "A horrible curse has befallen you!"
#define STRING_NORTH                                                 "north"
#define STRING_SOUTH                                                 "south"
#define STRING_EAST                                                  "east"
#define STRING_WEST                                                  "west"
#define STRING_LEAGUE                                                "league"
#define STRING_LEAGUES                                               "leagues"

#define STRING_CHESTCOLLECT_KEY                                      "a key"
#define STRING_CHESTCOLLECT_HERB                                     "an herb"
#define STRING_CHESTCOLLECT_WING                                     "a wing"
#define STRING_CHESTCOLLECT_TORCH                                    "a torch"
#define STRING_CHESTCOLLECT_DRAGONSCALE                              "a Dragon's scale"
#define STRING_CHESTCOLLECT_TABLET                                   "Erdrick's Tablet"
#define STRING_CHESTCOLLECT_SILVERHARP                               "the Silver Harp"
#define STRING_CHESTCOLLECT_STONEOFSUNLIGHT                          "the Stone of Sunlight"
#define STRING_CHESTCOLLECT_CURSEDBELT                               "a Cursed Belt"
#define STRING_CHESTCOLLECT_DEATHNECKLACE                            "the Death Necklace"

#define STRING_ITEMUSE_HERB                                          "You grind up an herb and eat it."
#define STRING_ITEMUSE_WING                                          "You throw a wing into the air."
#define STRING_ITEMUSE_FAIRYWATER                                    "You drink a vial of fairy water."
#define STRING_ITEMUSE_WING_CANTUSE                                  "You cannot use a wing here."
#define STRING_ITEMUSE_TORCH_CANTUSE                                 "You cannot use a torch here."
#define STRING_ITEMUSE_TORCH_ALREADYUSED                             "A torch has already been lit."
#define STRING_ITEMUSE_TORCH_SPHEREOFLIGHT                           "The Sphere of Light burns much brighter than a torch!"
#define STRING_ITEMUSE_TORCH                                         "You light a torch."
#define STRING_ITEMUSE_FAIRYFLUTE_1                                  "You play the Fairy Flute."
#define STRING_ITEMUSE_FAIRYFLUTE_2                                  "A mysterious melody fills the air."
#define STRING_ITEMUSE_SILVERHARP_1                                  "You play the Silver Harp."
#define STRING_ITEMUSE_SILVERHARP_2                                  "Beautiful music flows from its glistening strings."
#define STRING_ITEMUSE_GWAELINSLOVE_CANTUSE                          "Gwaelin's Love cannot be used here."
#define STRING_ITEMUSE_GWAELINSLOVE_1                                "\"Heed my voice %s, for this is Gwaelin."
#define STRING_ITEMUSE_GWAELINSLOVE_2                                "To reach the next level you must raise your experience points by %u."
#define STRING_ITEMUSE_GWAELINSLOVE_3                                "From where you are now, my castle lies %s."
#define STRING_ITEMUSE_GWAELINSLOVE_3_HOME                           "underneath your very feet"
#define STRING_ITEMUSE_GWAELINSLOVE_3_SINGLE                         "%u %s to the %s"
#define STRING_ITEMUSE_GWAELINSLOVE_3_DOUBLE                         "%u %s to the %s and %u to the %s"
#define STRING_ITEMUSE_GWAELINSLOVE_4                                "I love you, %s!\""
#define STRING_ITEMUSE_RAINBOWDROP_CANTUSE                           "The Rainbow Drop cannot be used here."
#define STRING_ITEMUSE_RAINBOWDROP                                   "You pour the Rainbow Drop into the water."
#define STRING_ITEMUSE_CURSEDBELT                                    "You put on the Cursed Belt."

#define STRING_CHEST_ITEMFOUND                                       "The chest contains %s!"
#define STRING_CHEST_ITEMNOSPACE                                     "But you can't carry any more of these."
#define STRING_CHEST_GOLDFOUND                                       "The chest contains %u gold pieces!"
#define STRING_CHEST_GOLDNOSPACE                                     "But you can't carry any more gold."
#define STRING_CHEST_TABLET_1                                        "The tablet reads as follows..."
#define STRING_CHEST_TABLET_2                                        "\"I am Erdrick, and thou art my descendant.\""
#define STRING_CHEST_TABLET_3                                        "\"Three items are needed to reach the Isle of Dragons, which is south of Brecconary.\""
#define STRING_CHEST_TABLET_4                                        "\"I gathered these items, reached the Isle, and there defeated a creature of great evil.\""
#define STRING_CHEST_TABLET_5                                        "\"Now I have entrusted the three items to three worthy keepers.\""
#define STRING_CHEST_TABLET_6                                        "\"Their descendants will protect the items until thy quest leads thee to seek them out.\""
#define STRING_CHEST_TABLET_7                                        "\"When a new evil arises, find these three items, and defeat thy foe!\""
#define STRING_CHEST_TABLET_8                                        "The language is very old, but something about it resonates within you..."

#define STRING_FOUNDITEM_TOKEN                                       "Erdrick's Token"
#define STRING_FOUNDITEM_FAIRYFLUTE                                  "the Fairy Flute"
#define STRING_FOUNDITEM_ERDRICKSARMOR                               "Erdrick's Armor"

#define STRING_FOUND_HIDDENSTAIRS                                    "You found a hidden stairway!"
#define STRING_DEFEATED_DRAGONLORD_OVERWORLD                         "Now is not the time, you should return to Tantegel immediately!"

#define STRING_ENEMY_SLIME                                           "slime"
#define STRING_ENEMY_REDSLIME                                        "red slime"
#define STRING_ENEMY_METALSLIME                                      "metal slime"
#define STRING_ENEMY_DRAKEE                                          "drakee"
#define STRING_ENEMY_MAGIDRAKEE                                      "magidrakee"
#define STRING_ENEMY_DRAKEEMA                                        "drakeema"
#define STRING_ENEMY_GHOST                                           "ghost"
#define STRING_ENEMY_POLTERGEIST                                     "poltergeist"
#define STRING_ENEMY_SPECTER                                         "specter"
#define STRING_ENEMY_MAGICIAN                                        "magician"
#define STRING_ENEMY_WARLOCK                                         "warlock"
#define STRING_ENEMY_WIZARD                                          "wizard"
#define STRING_ENEMY_SCORPION                                        "scorpion"
#define STRING_ENEMY_METALSCORPION                                   "metal scorpion"
#define STRING_ENEMY_ROGUESCORPION                                   "rogue scorpion"
#define STRING_ENEMY_DRUIN                                           "druin"
#define STRING_ENEMY_DRUINLORD                                       "druinlord"
#define STRING_ENEMY_DROLL                                           "droll"
#define STRING_ENEMY_DROLLMAGI                                       "drollmagi"
#define STRING_ENEMY_SKELETON                                        "skeleton"
#define STRING_ENEMY_WRAITH                                          "wraith"
#define STRING_ENEMY_WRAITHKNIGHT                                    "wraith knight"
#define STRING_ENEMY_DEMONKNIGHT                                     "demon knight"
#define STRING_ENEMY_WOLF                                            "wolf"
#define STRING_ENEMY_WOLFLORD                                        "wolflord"
#define STRING_ENEMY_WEREWOLF                                        "werewolf"
#define STRING_ENEMY_GOLDMAN                                         "goldman"
#define STRING_ENEMY_GOLEM                                           "golem"
#define STRING_ENEMY_STONEMAN                                        "stoneman"
#define STRING_ENEMY_WYVERN                                          "wyvern"
#define STRING_ENEMY_MAGIWYVERN                                      "magiwyvern"
#define STRING_ENEMY_STARWYVERN                                      "starwyvern"
#define STRING_ENEMY_KNIGHT                                          "knight"
#define STRING_ENEMY_AXEKNIGHT                                       "axe knight"
#define STRING_ENEMY_ARMOREDKNIGHT                                   "armored knight"
#define STRING_ENEMY_GREENDRAGON                                     "green dragon"
#define STRING_ENEMY_BLUEDRAGON                                      "blue dragon"
#define STRING_ENEMY_REDDRAGON                                       "red dragon"
#define STRING_ENEMY_DRAGONLORD                                      "Dragonlord"

#define STRING_BATTLE_COMMAND                                        "Command?"
#define STRING_BATTLE_ENEMYAPPROACHES                                "%s approaches!"
#define STRING_BATTLE_ENEMYAPPROACHESINITIATIVE                      "%s approaches! Command?"
#define STRING_BATTLE_ENEMYINITIATIVE                                "The %s gets the jump on you!"
#define STRING_BATTLE_DRAGONLORDINITIATIVE                           "The Dragonlord launches a sneak attack!"
#define STRING_BATTLE_ATTACKATTEMPT                                  "You attack!"
#define STRING_BATTLE_ATTACKSUCCEEDED                                "The %s has lost %u hit %s."
#define STRING_BATTLE_ATTACKEXCELLENTMOVE                            "Excellent move! The %s has lost %u hit %s."
#define STRING_BATTLE_ATTACKDODGED                                   "But the %s dodges your attack!"
#define STRING_BATTLE_ATTACKINEFFECTIVE                              "Your weapon is ineffective against the %s!"
#define STRING_BATTLE_FLEEATTEMPT                                    "You make a run for it..."
#define STRING_BATTLE_FLEEATTEMPTSUCCEEDED                           "You have eluded the %s!"
#define STRING_BATTLE_FLEEATTEMPTFAILED                              "But the %s blocks your escape!"
#define STRING_BATTLE_ENEMYASLEEP                                    "The %s is asleep! Command?"
#define STRING_BATTLE_ENEMYFIZZLED                                   "The %s's spells have been blocked!"
#define STRING_BATTLE_VICTORY                                        "The %s is defeated!"
#define STRING_BATTLE_PLAYERSTILLASLEEP                              "You are still asleep!"
#define STRING_BATTLE_PLAYERWOKEUP                                   "You have awoken! Command?"
#define STRING_BATTLE_ENEMYSTILLASLEEP                               "The %s is still asleep. Command?"
#define STRING_BATTLE_ENEMYWOKEUP                                    "The %s woke up!"
#define STRING_BATTLE_EXPERIENCEANDGOLD                              "You have gained %u experience %s and %u gold."
#define STRING_BATTLE_EXPERIENCEONLY                                 "You have gained %u experience %s."
#define STRING_BATTLE_GOLDONLY                                       "You have gained %u gold."
#define STRING_BATTLE_LEVELUP                                        "This experience has pushed you to a higher level!"
#define STRING_BATTLE_STRENGTHGAIN                                   "Your strength has increased by %u."
#define STRING_BATTLE_AGILITYGAIN                                    "Your agility has increased by %u."
#define STRING_BATTLE_STRENGTHANDAGILITYGAIN                         "Your strength has increased by %u, and agility by %u."
#define STRING_BATTLE_HITPOINTSGAIN                                  "Your max hit points have increased by %u."
#define STRING_BATTLE_MAGICPOINTSGAIN                                "Your max magic points have increased by %u."
#define STRING_BATTLE_HITPOINTSANDMAGICPOINTSGAIN                    "Your max hit points have increased by %u, and max magic points by %u."
#define STRING_BATTLE_LEARNEDSPELL                                   "You learned a new spell, %s!"
#define STRING_BATTLE_NOSPELLS                                       "You do not know any spells. Command?"
#define STRING_BATTLE_CANTCASTSPELL                                  "You do not know any spells that can be cast in battle. Command?"
#define STRING_BATTLE_NOTENOUGHMP                                    "You do not have enough MP. Command?"
#define STRING_BATTLE_SPELLCAST                                      "You cast %s!"
#define STRING_BATTLE_SPELLFIZZLED                                   "But the spell has been blocked!"
#define STRING_BATTLE_SPELLFIZZLEDCOMMAND                            "But the spell has been blocked! Command?"
#define STRING_BATTLE_FULLYHEALED                                    "You are already fully healed. Command?"
#define STRING_BATTLE_SPELL_NOEFFECT                                 "But the spell has no effect on the %s!"
#define STRING_BATTLE_SPELL_SLEEP_ALREADYASLEEP                      "The %s is already asleep. Command?"
#define STRING_BATTLE_SPELL_FIZZLE_ALREADYFIZZLED                    "The %s's spells are already blocked. Command?"
#define STRING_BATTLE_NOITEMS                                        "You do not have any items. Command?"
#define STRING_BATTLE_CANTUSEITEM                                    "You do not have any items that can be used in battle. Command?"
#define STRING_BATTLE_ENEMY_ATTACKATTEMPT                            "The %s attacks!"
#define STRING_BATTLE_ENEMY_BREATHEFIRE                              "The %s breathes fire!"
#define STRING_BATTLE_ENEMY_ATTACKDODGED                             "But you dodge the attack! Command?"
#define STRING_BATTLE_ENEMY_ATTACKSUCCEEDED                          "You have lost %u hit %s. Command?"
#define STRING_BATTLE_ENEMY_ATTACKSUCCEEDEDASLEEP                    "You have lost %u hit %s."
#define STRING_BATTLE_ENEMY_ATTACKDEATH                              "You have lost %u hit %s."
#define STRING_BATTLE_ENEMY_SPELLCAST                                "The %s casts %s!"
#define STRING_BATTLE_ENEMY_RECOVERED                                "The %s has recovered. Command?"
#define STRING_BATTLE_ENEMY_RECOVEREDASLEEP                          "The %s has recovered."
#define STRING_BATTLE_PLAYER_FIZZLED                                 "Your spell has been blocked! Command?"
#define STRING_BATTLE_PLAYER_FIZZLEDASLEEP                           "Your spell has been blocked!"
#define STRING_BATTLE_PLAYER_ASLEEP                                  "You are asleep!"
#define STRING_BATTLE_PLAYER_SPELL_NOEFFECT                          "But the spell has no effect! Command?"
#define STRING_BATTLE_PLAYER_SPELL_NOEFFECTASLEEP                    "But the spell has no effect!"
#define STRING_BATTLE_ENEMY_FLEE                                     "The %s turns and runs away!"
#define STRING_BATTLE_DRAGONLORD_WIZARDINTRO                         "The Dragonlord prepares for battle!"
#define STRING_BATTLE_DRAGONLORD_DRAGONINTRO                         "The Dragonlord reveals its true form!"

#define STRING_BATTLE_MENU_TITLE                                     "COMMAND"
#define STRING_BATTLE_MENU_ATTACK                                    "ATTACK"
#define STRING_BATTLE_MENU_FLEE                                      "FLEE"
#define STRING_BATTLE_MENU_SPELL                                     "SPELL"
#define STRING_BATTLE_MENU_ITEM                                      "ITEM"

#define STRING_INN_WELCOME                                           "\"Welcome to the Traveler's Inn! One night's stay is %u gold, would you like a room?\""
#define STRING_INN_TOOEXPENSIVE_1                                    "\"It seems you are a bit short on gold, unfortunately we cannot accommodate you.\""
#define STRING_INN_TOOEXPENSIVE_2                                    "\"Please come back when you have acquired sufficient funds!\""
#define STRING_INN_STAY                                              "\"Enjoy your stay!\""
#define STRING_INN_LEAVE                                             "\"Come back anytime, our door is always open!\""
#define STRING_INN_MORNING                                           "\"We hope you rested well, be safe in your travels!\""

#define STRING_WEAPONSHOP_WELCOMEBUYSELL                             "\"Welcome! We deal in weapons and armor, how can I help you?\""
#define STRING_WEAPONSHOP_WELCOMEVIEWCHOICE                          "\"Welcome! We deal in weapons and armor, would you like to see our wares?\""
#define STRING_WEAPONSHOP_VIEWITEMS                                  "\"What would you like to purchase?\""
#define STRING_WEAPONSHOP_LEAVE                                      "\"We hope you drop by again!\""
#define STRING_WEAPONSHOP_TOOEXPENSIVE                               "\"Sorry, but it appears you don't have enough gold for this item.\""
#define STRING_WEAPONSHOP_ERDRICKSSWORD                              "\"This weapon is no match for the one you carry, I'm afraid I cannot allow it!\""
#define STRING_WEAPONSHOP_ERDRICKSARMOR                              "\"Your current armor is irreplaceable, I'm afraid I cannot allow it!\""
#define STRING_WEAPONSHOP_ALREADYHAVE                                "\"Whoops, it appears you already have this item!\""
#define STRING_WEAPONSHOP_AREYOUSURE1                                "\"You'd like to purchase the %s, are you sure?\""
#define STRING_WEAPONSHOP_AREYOUSURE2                                "\"You'd like to purchase the %s %s, are you sure?\""
#define STRING_WEAPONSHOP_RESELL                                     "\"Then I will trade in your %s for %u gold, is that alright?\""
#define STRING_WEAPONSHOP_ANYTHINGELSE                               "\"Does anything else catch your eye?\""
#define STRING_WEAPONSHOP_THANKYOU                                   "\"Thank you for your purchase! Does anything else catch your eye?\""
#define STRING_WEAPONSHOP_CANNOTSELLWEAPON_1                         "\"Uh oh, looks like your pockets are full!\""
#define STRING_WEAPONSHOP_CANNOTSELLWEAPON_2                         "\"Would you like to take a look at our wares?\""
#define STRING_WEAPONSHOP_SELLWHICHWEAPON                            "\"What would you like to sell today?\""
#define STRING_WEAPONSHOP_ANYMOREBUSINESS                            "\"Will there be anything else today?\""
#define STRING_WEAPONSHOP_THANKYOUNOTHINGTOSELL                      "\"Pleasure doing business with you! It seems you have nothing more to sell...\""

#define STRING_ITEMSHOP_WELCOMEVIEWCHOICE                            "\"Welcome! We deal in tools, would you like to see our inventory?\""
#define STRING_ITEMSHOP_WELCOMEBUYSELL                               "\"Welcome! We deal in tools, what would you like to do today?\""
#define STRING_ITEMSHOP_VIEWITEMS                                    "\"What would you like to purchase?\""
#define STRING_ITEMSHOP_CANNOTSELLITEM_1                             "\"Goodness me, I'm afraid you can't carry any more gold!\""
#define STRING_ITEMSHOP_CANNOTSELLITEM_2                             "\"Would you like to browse our inventory instead?\""
#define STRING_ITEMSHOP_SELLWHICHITEM                                "\"I see, and which item are you looking to sell?\""
#define STRING_ITEMSHOP_SELLAREYOUSURE                               "\"The %s? I can give you %u gold for that, is that okay?\""
#define STRING_ITEMSHOP_ANYMOREBUSINESS                              "\"Will there be anything else?\""
#define STRING_ITEMSHOP_LEAVE                                        "\"Have a wonderful day!\""
#define STRING_ITEMSHOP_TOOEXPENSIVE                                 "\"Oh no, it seems you don't have enough gold, sorry!\""
#define STRING_ITEMSHOP_NOSPACE                                      "\"Whoops, it seems you can't carry any more of these!\""
#define STRING_ITEMSHOP_AREYOUSURE1                                  "\"One %s, are you sure?\""
#define STRING_ITEMSHOP_AREYOUSURE2                                  "\"One %s %s, are you sure?\""
#define STRING_ITEMSHOP_ANYTHINGELSE                                 "\"Would you like to purchase anything else?\""
#define STRING_ITEMSHOP_THANKYOU                                     "\"Thank you very much! Would you like to purchase anything else?\""
#define STRING_ITEMSHOP_THANKYOUSELL                                 "\"Pleasure doing business with you! Will there be anything else?\""
#define STRING_ITEMSHOP_THANKYOUNOTHINGTOSELL                        "\"Pleasure doing business with you! It seems you have no more items to sell...\""

#define STRING_KEYSHOP_WELCOME                                       "\"All-purpose keys! They unlock any door, one-use only! %u gold, are you in?\""
#define STRING_KEYSHOP_LEAVE                                         "\"You know where to find me!\""
#define STRING_KEYSHOP_TOOEXPENSIVE                                  "\"I'm afraid you're short on funds, come back when you've got the goods!\""
#define STRING_KEYSHOP_NOSPACE                                       "\"You can't carry any more keys, I'm afraid I can't sell!\""
#define STRING_KEYSHOP_THANKYOU                                      "\"Appreciated, how about another one?\""

#define STRING_FAIRYWATERSHOP_PURCHASE                               "\"Traveler, will you buy a vial of Fairy Water for 38 gold to keep the Dragonlord's minions away?\""
#define STRING_FAIRYWATERSHOP_TOOEXPENSIVE                           "\"Oh I'm terribly sorry, but it appears you are low on gold, please come back again later!\""
#define STRING_FAIRYWATERSHOP_NOSPACE                                "\"My mistake, I didn't realize your pouch is already full. Be safe on your travels!\""
#define STRING_FAIRYWATERSHOP_THANKYOU                               "\"Thank you very much! How about another vial?\""
#define STRING_FAIRYWATERSHOP_LEAVE                                  "\"Be safe on your travels!\""

#define STRING_BOOTH_TANTEGELWIZARD                                  "\"May the light shine upon the brave hero, descendant of Erdrick!\""
#define STRING_BOOTH_KOLWIZARD1                                      "\"I sense that your bravery matches that of the legendary hero Erdrick himself!\""
#define STRING_BOOTH_KOLWIZARD2                                      "\"However, defeating the Dragonlord requires more than bravery.\""
#define STRING_BOOTH_KOLWIZARD3                                      "\"It is said that his scales are harder than steel, and almost impenetrable!\""
#define STRING_BOOTH_KOLWIZARD4                                      "\"Legends say only Erdrick's Sword is capable of this feat, but the sword has been lost in time.\""
#define STRING_BOOTH_KOLWIZARD5                                      "\"Some believe the Dragonlord himself found it, but was unable to destroy it...\""
#define STRING_BOOTH_KOLWIZARD6                                      "\"I believe one as clever as the Dragonlord would likely want to keep such a weapon close to him!\""
#define STRING_BOOTH_KOLWIZARD7                                      "\"I see you have discovered Erdrick's Sword, you are indeed as brave as I sensed!\""
#define STRING_BOOTH_KOLWIZARD8                                      "\"Now is the time to face the Dragonlord in combat, I am more hopeful than ever!\""
#define STRING_BOOTH_CANTLINWIZARD                                   "\"Legends say that Erdrick's Sword could cleave steel!\""
#define STRING_BOOTH_CANTLINRADISHES                                 "\"Radishes!! Fresh and cheap, this is your one-stop shop for radishes, please buy them today!\""
#define STRING_BOOTH_CANTLINWYNN1                                    "\"My grandfather Wynn once owned a shop on the east side of Hauksness.\""
#define STRING_BOOTH_CANTLINWYNN2                                    "\"I wonder what still remains of that place?\""
#define STRING_BOOTH_RIMULDARWIZARD1                                 "\"It is said there is a shrine to the south where great magic exists.\""
#define STRING_BOOTH_RIMULDARWIZARD2                                 "\"According to legend, it is a place where the sun and rain are destined to meet.\""
#define STRING_BOOTH_RIMULDARWIZARD3                                 "\"You have visited the southern shrine, haven't you? I can sense it!\""

#define STRING_NPC_DEFAULT                                           "No response. How rude."
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_1_1                      "\"Hello %s, I am relieved to see you have returned safely!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_1_2                      "\"Hello %s, Gwaelin and I are relieved to see you have returned safely!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_2                        "\"I sense that you'll require %u more experience %s to reach a higher level...\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_3                        "\"...\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_4                        "King Lorik suddenly convulses grotesquely..."
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_5                        "\"Your progress... remember...\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_6                        "\"%s\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_7                        "\"...\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_8                        "The king snaps out of it and can't remember a thing. What did he mean??"
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_INTRO_1_1                "\"%s, welcome to Tantegel Castle! Your presence brings a glimmer of hope to my people.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_INTRO_1_2                "\"I am told you are the descendant of the legendary hero, Erdrick.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_INTRO_1_3                "\"It is said that in ages past Erdrick defeated a great evil using a Sphere of Light.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_INTRO_1_4                "\"Then came the Dragonlord, and with him came destruction and despair.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_INTRO_1_5                "\"The Dragonlord stole the precious Sphere of Light and hid it in the darkness.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_INTRO_1_6                "\"It is my understanding that, as Erdrick's descendant, you wish to help us.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_INTRO_1_7                "\"The Dragonlord must be defeated!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_INTRO_1_8                "\"Take now whatever you may find in these chests to aid you in your quest.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_INTRO_1_9                "\"Speak with the guards as well, they have knowledge that will surely help.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_INTRO_1_10               "\"Go now, %s, and may the light shine upon you!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_INTRO_2_1                "\"When you've finished preparing for your journey, please come and see me.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_INTRO_3_1                "\"Welcome back, %s! You look quite well-rested.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_INTRO_3_2                "\"It is time to resume your quest, may the light shine upon you!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_THANKS_1                 "\"My dearest Gwaelin! You've returned home!!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_THANKS_2                 "\"But who... how did...? You say %s came to your rescue?\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_THANKS_3                 "\"%s, you are even more brave than I could have imagined!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_THANKS_4                 "\"You have my everlasting gratitude, I thank you from the bottom of my heart.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_THANKS_5                 "Princess Gwaelin removes a small chain with a locket from her neck."
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_THANKS_6                 "Gwaelin: \"%s, I would like you to have this.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_THANKS_7                 "\"It is a symbol of my love, for you have stolen my heart.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_THANKS_8                 "\"Please take it with you, so that even across great distances we can still be together.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_THANKS_9                 "\"I love you, %s!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_THANKS_10                "King Lorek sheds a tear of joy as you take Gwaelin's locket in your hand."
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_THANKS_11                "It feels as if you can tell Gwaelin's exact location just by looking at it."
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_THANKS_12                "Lorik: \"All hail %s, our courageous hero!!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_DEATH_1                  "\"%s, what a terrible thing, my soldiers found you and thought you had died!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_DEATH_2                  "\"Against all odds, my people were able to nurse you back to health, what a relief!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_DEATH_3                  "\"Please be more careful in your travels, next time you may not be so lucky!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_CURSED_1                 "\"My soldiers brought you back from the brink of death, yet what is this...\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_CURSED_2                 "\"You've brought a CURSE into these halls with you, this I cannot allow!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_KING_CURSED_3                 "\"Begone %s! Soldiers, remove him!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_PRINCESS_1                    "\"My savior, my champion, you who have stolen my heart...\""
#define STRING_NPC_TANTEGEL_THRONEROOM_PRINCESS_2                    "\"I love you, %s!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_PRINCESS_3                    "\"I will be thinking of you every moment you're away on your quest...\""
#define STRING_NPC_TANTEGEL_THRONEROOM_PRINCESS_4                    "\"But I also know in my heart that you will always return to me.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_LEFTSOLDIER_1                 "\"If I may offer a word of advice...\""
#define STRING_NPC_TANTEGEL_THRONEROOM_LEFTSOLDIER_2                 "\"Save your money for more expensive armor!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_LEFTSOLDIER_PR                "\"Princess Gwaelin has returned, incredible!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_LEFTSOLDIER_INTRO_1           "\"East of this castle is a town where you can purchase armor, weapons, and other items.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_LEFTSOLDIER_INTRO_2           "\"You can also stay at the Inn if you find yourself wounded, sleep heals all.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_RIGHTSOLDIER                  "\"It's best to try and listen to what people say, it could be of great help!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_RIGHTSOLDIER_PR               "\"It's the Princess, she's saved!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_RIGHTSOLDIER_INTRO_1_1        "\"I think one of the chests around here contains a key that will open this door.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_RIGHTSOLDIER_INTRO_1_2        "\"Be careful with your keys, they tend to break after a single use.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_RIGHTSOLDIER_INTRO_2          "\"Oh good, you got the door open!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_MOVINGSOLDIER_1               "\"Six months ago the King's daughter, Princess Gwaelin, was kidnapped.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_MOVINGSOLDIER_2               "\"Rumor has it a dragon swept her up and flew her away to a cave somewhere.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_MOVINGSOLDIER_3               "\"The King does not speak of it, but we can tell he suffers every day.\""
#define STRING_NPC_TANTEGEL_THRONEROOM_MOVINGSOLDIER_APR             "\"It's good to see you again %s, may good fortune always be with you!\""
#define STRING_NPC_TANTEGEL_THRONEROOM_MOVINGSOLDIER_PR              "\"King Lorik will be so relieved, you must speak to him!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_STAIRSUPPERSOLDIER_1         "\"King Lorik has recently been heard speaking what seems to be gibberish.\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_STAIRSUPPERSOLDIER_2         "\"Some say only the descendants of Erdrick can understand him.\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_STAIRSUPPERSOLDIER_PR        "\"You must go upstairs to see the King immediately!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_STAIRSLOWERSOLDIER           "\"Guard duty is quite boring.\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_STAIRSLOWERSOLDIER_PR        "\"How exciting, Princess Gwaelin has been rescued!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_BOTTOMRIGHTSTATICSOLDIER_1   "\"One day, I will have Princess Gwaelin's hand in marriage, you'll see!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_BOTTOMRIGHTSTATICSOLDIER_2   "\"Oh Gwaelin, my love..... please just get out of my sight!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_BOTTOMRIGHTSTATICSOLDIER_PR  "The guard looks at Gwaelin and is rendered speechless."
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_BOTTOMRIGHTSTATICSOLDIER_DF  "\"You truly are a hero, I see now why Gwaelin loves you... *sob*\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_ENTRYLEFTSOLDIER             "\"Welcome to Tantegel Castle!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_ENTRYLEFTSOLDIER_PR          "\"Wow, Princess Gwaelin! What wonderful news!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_ENTRYLEFTSOLDIER_DF          "\"%s, the King is waiting for you!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_ENTRYRIGHTSOLDIER_1          "\"Bienvenido al castillo de Tantegel!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_ENTRYRIGHTSOLDIER_2          "\"...I've been practicing, how did I do?\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_ENTRYRIGHTSOLDIER_PR         "\"La princesa esta salvada, esto es maravilloso!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_ENTRYRIGHTSOLDIER_DF         "\"Esta mar... uh, es muy bien al..? Oh, forget it, today is a wonderful day!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_UPPERLEFTSTATICBLUEMAN       "\"If you face enough foes, you'll become strong enough to battle fierce enemies.\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_UPPERLEFTSTATICBLUEMAN_PR    "\"I knew it, I knew you could save Princess Gwaelin! Bravo!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_UPPERLEFTSTATICBLUEMAN_DF    "\"At last, our faith as been rewarded, these are magnificent times!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_UPPERRIGHTSTATICBLUEWOMAN_1  "\"When the sun and rain meet, a rainbow bridge shall appear.\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_UPPERRIGHTSTATICBLUEWOMAN_2  "\"At least, that's what legends say. I wonder what it means?\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_UPPERRIGHTSTATICBLUEWOMAN_PR "\"Is it really the Princess? How wonderful!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_UPPERRIGHTSTATICBLUEWOMAN_DF "\"Can it be true, the Dragonlord is really gone?!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_STATICBARRIERSOLDIER         "\"I wouldn't go in there if your hit points are low.\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_STATICBARRIERSOLDIER_DF      "\"Interesting, the barrier seems safe to cross now, I wonder what happened?\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_STAIRSBLUEMAN                "\"There was a time when Brecconary was a paradise. Then the Dragonlord's minions came.\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_STAIRSBLUEMAN_PR             "\"The Princess is saved! These are good tidings, indeed!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_COURTYARDBLUEWOMAN_1         "\"I hope and pray each day that the Princess is returned safely!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_COURTYARDBLUEWOMAN_2         "\"You have my eternal gratitude for rescuing the Princess, you are a true hero!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_COURTYARDBLUEWOMAN_PR        "\"My prayers have been answered, Princess Gwaelin has been rescued!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_LOWERLEFTGREENMANRIGHT_1     "\"We are merchants who have traveled all over the land of Alefgard.\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_LOWERLEFTGREENMANRIGHT_2     "\"Many of our colleagues have been killed by servants of the Dragonlord.\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_LOWERLEFTGREENMANRIGHT_PR    "\"Only a true hero could have saved the Princess, the Dragonlord should be afraid!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_LOWERLEFTGREENMANRIGHT_DF    "\"Our colleagues have been avenged, all thanks to this brave hero!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_LOWERLEFTGREENMANLEFT        "\"Rumor has it that entire towns have been destroyed by the Dragonlord's servants.\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_LOWERLEFTGREENMANLEFT_PR     "\"Oh my, it's Princess Gwaelin! You should see King Lorik immediately!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_LOWERLEFTGREENMANLEFT_DF     "\"We're all so grateful for this incredible deed, thank you so much!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_TREASUREROOMSOLDIER_1        "\"I've always been told that brave men never steal.\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_TREASUREROOMSOLDIER_2        "\"...but for the hero tasked with saving the world, I suppose extra supplies can't hurt.\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_TREASUREROOMSOLDIER_PR       "\"Pr... Princess Gwaelin, your highness! King Lorik will be so happy to see you!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_TREASUREROOMSOLDIER_DF       "\"%s, we've all heard the news, what an incredible feat you've pulled off!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_UPPERSOLDIER                 "\"Doors won't open without a key.\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_UPPERSOLDIER_PR              "\"It's the Princess! She has returned to us safely!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_UPPERSOLDIER_DF              "\"All hail the courageous descendant of Erdrick!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_RIGHTACTIVESOLDIER           "\"I've been looking for the castle cellar for over an hour, I heard it's difficult to find!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_RIGHTACTIVESOLDIER_PR        "\"Princess Gwaelin, it's really you!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_RIGHTACTIVESOLDIER_DF        "\"I finally found the castle cellar, and now this! Today is my lucky day!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_ACTIVEWIZARD                 "\"Let us all wish the warrior well on his journey, may the light be your strength!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_ACTIVEWIZARD_PR              "\"Erdrick's descendant has rescued the Princess, what an incredible deed!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_ACTIVEWIZARD_DF              "\"The future is looking very bright, all thanks to you, %s!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_PASTBARRIERSOLDIER_1         "\"Garin's grave is said to be located in Garinham.\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_PASTBARRIERSOLDIER_2         "\"Rumor has it that you must push on a wall of darkness to find it.\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_PASTBARRIERSOLDIER_PR        "\"Amazing, the Princess has been rescued! Quick, report this to King Lorik!\""
#define STRING_NPC_TANTEGEL_GROUNDFLOOR_PASTBARRIERSOLDIER_DF        "\"Incredible, we're all saved! And I can finally leave this dreadful room!\""
#define STRING_NPC_TANTEGEL_BASEMENT_WIZARD_1                        "\"I have waited a long time for one such as you to arrive. Take this treasure so that I may finally rest.\""
#define STRING_NPC_TANTEGEL_BASEMENT_WIZARD_2                        "\"If your business here is finished, please leave me at peace.\""
#define STRING_NPC_TANTEGEL_BASEMENT_WIZARD_DF_1                     "\"At long last the Dragonlord is no longer of this world.\""
#define STRING_NPC_TANTEGEL_BASEMENT_WIZARD_DF_2                     "\"Now I can truly rest, please leave this old man at peace.\""
#define STRING_NPC_BRECCONARY_WESTENTRANCEBLUEMAN                    "\"Welcome to the town of Brecconary!\""
#define STRING_NPC_BRECCONARY_WEAPONSHOPBLUEWOMAN                    "\"Welcome! To purchase equipment, speak to my father across the desk.\""
#define STRING_NPC_BRECCONARY_LEFTROOMBLUEMAN                        "\"Somewhere in Alefgard there is a shop that sells keys, I hope to go there one day!\""
#define STRING_NPC_BRECCONARY_RIGHTROOMWIZARD1                       "\"Should you find yourself cursed, come and see me.\""
#define STRING_NPC_BRECCONARY_RIGHTROOMWIZARD2                       "\"You were right to seek me out, a curse has certainly befallen you!\""
#define STRING_NPC_BRECCONARY_RIGHTROOMWIZARD3                       "\"Now hold still...\""
#define STRING_NPC_BRECCONARY_RIGHTROOMWIZARD4                       "\"Oh Great Goddess, please hear my words! Behold, our brave hero has been cursed!\""
#define STRING_NPC_BRECCONARY_RIGHTROOMWIZARD5                       "\"Let us not lose hope in the one destined to rid this land of evil, and lift this curse!\""
#define STRING_NPC_BRECCONARY_RIGHTROOMWIZARD6                       "\"...\""
#define STRING_NPC_BRECCONARY_RIGHTROOMWIZARD7                       "\"It... it worked! The curse has been lifted.\""
#define STRING_NPC_BRECCONARY_RIGHTROOMWIZARD8                       "\"I am quite tired now... please, I must rest.\""
#define STRING_NPC_BRECCONARY_INNSTATICSOLDIER                       "\"Who's touching me?! I can neither see nor hear!\""
#define STRING_NPC_BRECCONARY_LOWERRIGHTSTATICBLUEMAN_1              "\"Our door is always open, come on in!\""
#define STRING_NPC_BRECCONARY_LOWERRIGHTSTATICBLUEMAN_2              "\"Be sure to take a look at our Dragon's Scales, they're our best seller.\""
#define STRING_NPC_BRECCONARY_LOWERRIGHTSTATICBLUEMAN_3              "\"In these trying times, wearing one can help protect you from danger!\""
#define STRING_NPC_BRECCONARY_UPPERRIGHTSOLDIER_1                    "\"Beware of bridges, danger tends to increase when crossing them, you could get hurt!\""
#define STRING_NPC_BRECCONARY_UPPERRIGHTSOLDIER_2                    "\"I suggest carrying some herbs with you, they can heal your injuries.\""
#define STRING_NPC_BRECCONARY_UPPERWIZARD                            "\"Swamps are poisonous, watch your hit points if you plan to step into one!\""
#define STRING_NPC_BRECCONARY_UPPERGREENMAN                          "\"Brave hero, please save us all from the wrath of the Dragonlord!\""
#define STRING_NPC_BRECCONARY_CENTERBLUEMAN_1                        "\"If you travel north to the seashore, you can follow the coastline west to reach Garinham.\""
#define STRING_NPC_BRECCONARY_CENTERBLUEMAN_2                        "\"I've heard there's a mysterious cave somewhere along the way, where magic has no effect.\""
#define STRING_NPC_BRECCONARY_CENTERBLUEMAN_3                        "\"I plan to explore that cave one day, and when I do, I'll be sure to bring a torch!\""
#define STRING_NPC_BRECCONARY_CENTERREDSOLDIER_1                     "\"Many warriors have sought to defeat the Dragonlord, but all but one have perished.\""
#define STRING_NPC_BRECCONARY_CENTERREDSOLDIER_2                     "\"He's lucky to be alive, but unfortunately it cost him his eyes as well as his ears.\""
#define STRING_NPC_BRECCONARY_CENTERREDSOLDIER_3                     "\"Yet I sense something different about you, %s, I pray that you succeed!\""
#define STRING_NPC_BRECCONARY_EASTOFINNBLUEWOMAN                     "\"Tee-hee! I'm sorry, but no, I am not Princess Gwaelin.\""
#define STRING_NPC_BRECCONARY_RIGHTSOLDIER                           "\"If your experience in battle has increased significantly, it may be helpful to visit King Lorik.\""
#define STRING_NPC_BRECCONARY_LOWERRIGHTACTIVEBLUEMAN_1              "\"From Tantegel Castle, across the water Charlock Castle is visible.\""
#define STRING_NPC_BRECCONARY_LOWERRIGHTACTIVEBLUEMAN_2              "\"That is the fortress of the Dragonlord, I would steer clear!\""
#define STRING_NPC_BRECCONARY_INNACTIVESOLDIER_1                     "\"Some say that Garin is buried in a deep grave somewhere in Alefgard...\""
#define STRING_NPC_BRECCONARY_INNACTIVESOLDIER_2                     "\"And though the grave is infested with the Dragonlord's minions, a Silver Harp is buried somewhere within.\""
#define STRING_NPC_GARINHAMOUTSIDE_LOWERLEFTWIZARD_1                 "\"Many believe that Princess Gwaelin is hidden away in a cave.\""
#define STRING_NPC_GARINHAMOUTSIDE_LOWERLEFTWIZARD_2                 "\"The rumors were true, Princess Gwaelin was indeed hidden away in a cave.\""
#define STRING_NPC_GARINHAMOUTSIDE_LEFTWIZARD                        "\"Garin is a wandering minstrel of legendary fame. He is said to have built this town.\""
#define STRING_NPC_GARINHAMOUTSIDE_SOLDIER_1                         "\"Have you met Nester? Great guy, you should meet him!\""
#define STRING_NPC_GARINHAMOUTSIDE_SOLDIER_2                         "\"One time he told me about a village far to the east, I think it was called Kol.\""
#define STRING_NPC_GARINHAMOUTSIDE_SOLDIER_3                         "\"He said he found a shrine to the west of Kol where a strange old man lived, classic Nester!\""
#define STRING_NPC_GARINHAMOUTSIDE_BLUEWOMAN                         "\"Welcome to Garinham, enjoy your stay here!\""
#define STRING_NPC_GARINHAMOUTSIDE_BLUEMAN_1_1                       "\"I've heard rumors that the Princess was kidnapped and taken to a cave to the east.\""
#define STRING_NPC_GARINHAMOUTSIDE_BLUEMAN_1_2                       "\"Although, there's another cave in the mountains to the south of here, maybe she was taken there?\""
#define STRING_NPC_GARINHAMOUTSIDE_BLUEMAN_1_3                       "\"I hope that isn't the case, legends say an object of great misfortune resides there.\""
#define STRING_NPC_GARINHAMOUTSIDE_BLUEMAN_1_4                       "\"If the stories are true, there's a chest that contains either great treasure or great peril.\""
#define STRING_NPC_GARINHAMOUTSIDE_BLUEMAN_2                         "\"I've heard rumors that the princess has been rescued, I hope they are true!\""
#define STRING_NPC_GARINHAMINSIDE_LEFTGUARD                          "\"I'm a little busy over here, could you ask the other guard?\""
#define STRING_NPC_GARINHAMINSIDE_RIGHTGUARD                         "\"I have no idea, try asking the other guard.\""
#define STRING_NPC_GARINHAMINSIDE_BLUEMAN                            "\"Once there was a town called Hauksness far to the south, I wonder if it's still there?\""
#define STRING_NPC_GARINHAMINSIDE_GREENMAN                           "\"I've learned that if I find myself in a dark place, it helps to make a map.\""
#define STRING_NPC_GARINHAMINSIDE_WIZARD_1                           "\"They say Erdrick wore a suit of armor that could withstand even a dragon's flame.\""
#define STRING_NPC_GARINHAMINSIDE_WIZARD_2                           "\"The armor was lost over time, hidden away somewhere.\""
#define STRING_NPC_GARINHAMINSIDE_BLUEWOMAN                          "\"I hate people, get away from me!\""
#define STRING_NPC_KOL_STATICRIGHTSOLDIER                            "\"To the east of Hauksness I've heard there's a town where one can find weapons of very fine quality!\""
#define STRING_NPC_KOL_STATICBLUEWOMAN                               "\"This bath cures rheumatism.\""
#define STRING_NPC_KOL_STATICLEFTSOLDIER                             "\"If you're looking for keys, Rimuldar is the place to go.\""
#define STRING_NPC_KOL_ENTRANCEWIZARD                                "\"Welcome to the village of Kol!\""
#define STRING_NPC_KOL_ENTRANCEBLUEMAN_1                             "\"The island to the south is quite dreadful, unless you have great strength I would stay away!\""
#define STRING_NPC_KOL_ENTRANCEBLUEMAN_2                             "\"If you decide to go anyway, you should take a wing with you, they can bring you back home safe.\""
#define STRING_NPC_KOL_COURTYARDBLUEWOMAN                            "\"Every day I pray for us all to be saved from the minions of the Dragonlord.\""
#define STRING_NPC_KOL_COURTYARDSOLDIER_1                            "\"A friend of mine from Cantlin told me a secret...\""
#define STRING_NPC_KOL_COURTYARDSOLDIER_2                            "\"He said the Golem is afraid of the Fairy's music.\""
#define STRING_NPC_KOL_COURTYARDBROWNSOLDIER_1                       "\"Have you met a guy named Nester by any chance? He's been everywhere!\""
#define STRING_NPC_KOL_COURTYARDBROWNSOLDIER_2                       "\"He told me once about a belt he found that he said was cursed, and warned me never to put it on.\""
#define STRING_NPC_KOL_COURTYARDBROWNSOLDIER_3                       "\"Then he said he had to go all the way to Brecconary to have it removed. Classic Nester!\""
#define STRING_NPC_KOL_LEFTWIZARD_1                                  "\"Legends say Erdrick's Armor is not only effective against enemy attacks...\""
#define STRING_NPC_KOL_LEFTWIZARD_2                                  "\"It also protects the wearer from environmental damage, how extraordinary!\""
#define STRING_NPC_KOL_LOWERLEFTGREENMAN_1                           "\"The town of Rimuldar is to the south of here, or so I've heard.\""
#define STRING_NPC_KOL_LOWERLEFTGREENMAN_2                           "\"Howard used to live here, but he set out to find Rimuldar and never returned.\""
#define STRING_NPC_KOL_LOWERLEFTGREENMAN_3                           "\"I miss him dearly, he used to play the Fairy Flute for us in the courtyard.\""
#define STRING_NPC_CANTLIN_UPPERLEFTSOLDIER_1                        "\"It's said that the Dragonlord has claws that can cleave iron and fiery breath that can melt stone!\""
#define STRING_NPC_CANTLIN_UPPERLEFTSOLDIER_2                        "\"If you still plan to face him, you must be a true hero!\""
#define STRING_NPC_CANTLIN_UPPERSOLDIER_1                            "\"Welcome to the castle town of Cantlin!\""
#define STRING_NPC_CANTLIN_UPPERSOLDIER_2                            "\"...wait, how did you get in here?\""
#define STRING_NPC_CANTLIN_UPPERRIGHTSOLDIER_1                       "\"Apparently Erdrick's Armor passed down from generation to generation.\""
#define STRING_NPC_CANTLIN_UPPERRIGHTSOLDIER_2                       "\"Eventually it wound up in Wynn's hands, and he hid it away somewhere.\""
#define STRING_NPC_CANTLIN_LEFTUPPERBLUEWOMAN                        "\"I can't decide what to eat for dinner...\""
#define STRING_NPC_CANTLIN_LEFTLOWERBLUEWOMAN                        "\"I'm sorry, but I can't help you, I've never left this town.\""
#define STRING_NPC_CANTLIN_NESTER_1                                  "\"Hey there, I'm Nester!\""
#define STRING_NPC_CANTLIN_NESTER_2                                  "\"I've never been to this town, it was really hard to sneak past the Golem.\""
#define STRING_NPC_CANTLIN_NESTER_3                                  "\"Have you been to the far southwest by chance? I found a really strange enemy there...\""
#define STRING_NPC_CANTLIN_NESTER_4                                  "\"It looked like a slime, but it was made of metal! It ran away before I could approach.\""
#define STRING_NPC_CANTLIN_NESTER_5                                  "\"We live in such a mysterious world, I can't wait to explore it further!\""
#define STRING_NPC_CANTLIN_RIGHTGREENMAN_1                           "\"My grandfather used to talk all the time about his friend, Wynn.\""
#define STRING_NPC_CANTLIN_RIGHTGREENMAN_2                           "\"He said Wynn came across something of great value, and buried it beneath the foot of a tree behind his shop.\""
#define STRING_NPC_CANTLIN_BARRIERWIZARD_1                           "\"Seek from the King's home, and ye shall find...\""
#define STRING_NPC_CANTLIN_BARRIERWIZARD_2                           "\"70 leagues to the south, 40 leagues to the east...\""
#define STRING_NPC_CANTLIN_BARRIERWIZARD_3                           "\"The Token of Erdrick, his descendant awaiteth!\""
#define STRING_NPC_CANTLINCOURTYARD_WIZARD                           "\"I've heard tell that someone in this very town knows where to find Erdrick's Token!\""
#define STRING_NPC_RIMULDAR_INNWIZARD_1                              "\"Good day to you, my name is Howard!\""
#define STRING_NPC_RIMULDAR_INNWIZARD_2                              "\"I'll let you in on a secret... take a look four paces south of the bath in Kol.\""
#define STRING_NPC_RIMULDAR_UPPERSTATICBLUEWOMAN                     "\"Who are you? Please leave me alone, or I'll call my friends over!\""
#define STRING_NPC_RIMULDAR_LEFTSTATICWIZARD_1                       "\"Legends say that Erdrick once created a rainbow bridge over the western part of this island.\""
#define STRING_NPC_RIMULDAR_LEFTSTATICWIZARD_2                       "\"They also say he entered the darkness from a hidden stairway in the throne room of the Dragonlord.\""
#define STRING_NPC_RIMULDAR_UPPERRIGHTEDGEBLUEMAN                    "\"Hi, I'm Orwick! I'm just waiting here for my girlfriend to arrive.\""
#define STRING_NPC_RIMULDAR_LOWERLEFTEDGEBLUEWOMAN                   "\"Ugh, Orwick is late again, as usual. I'm starving!\""
#define STRING_NPC_RIMULDAR_UPPERLEFTSTATICGREENMAN                  "\"Welcome!\""
#define STRING_NPC_RIMULDAR_ENTRANCEBLUEWOMAN                        "\"No, I have no tomatoes. I have no tomatoes today.\""
#define STRING_NPC_RIMULDAR_CENTERBLUEMAN                            "\"Welcome to the town of Rimuldar!\""
#define STRING_NPC_RIMULDAR_INNSOLDIER_1                             "\"Well if it isn't %s, I haven't seen you in quite some time, not since Tantegel!\""
#define STRING_NPC_RIMULDAR_INNSOLDIER_2                             "\"Another soldier from Tantegel was staying here recently, I think he was studying Spanish.\""
#define STRING_NPC_RIMULDAR_INNSOLDIER_3                             "\"Anyway, he just kind of disappeared one day and left his luggage behind.\""
#define STRING_NPC_RIMULDAR_INNSOLDIER_4                             "\"He was muttering something about his collection of 'alas' when it happened.\""
#define STRING_NPC_RIMULDAR_WEAPONSHOPSOLDIER                        "\"The scales of the Dragonlord are hard as steel, only Erdrick's Sword stands a chance against them!\""
#define STRING_NPC_RIMULDAR_UPPERROOMBLUEMAN                         "\"The woman in the other room isn't very nice, I was only trying to say hello.\""
#define STRING_NPC_RIMULDAR_LOWERLEFTSOLDIER                         "\"I've heard the Stone of Sunlight can be found in Tantegel castle, though not easily.\""
#define STRING_NPC_RIMULDAR_LOWERSOLDIER_1                           "\"Ahh, it's a lovely feeling to be single, isn't it? I feel so free!\""
#define STRING_NPC_RIMULDAR_LOWERSOLDIER_2                           "\"That look in your eye... are you in love? Don't tell me you plan to marry her, you're too young!\""
#define STRING_NPC_RIMULDARBUILDING_UPPERLEFTBLUEWOMAN               "\"Every day I get a more foreboding feeling, like the enemy is closing in.\""
#define STRING_NPC_RIMULDARBUILDING_LOWERLEFTBLUEMAN                 "\"If you plan on traveling south, I would advise against it, the enemies are terrifying!\""
#define STRING_NPC_RIMULDARBUILDING_LOWERRIGHTSOLDIER                "\"Does a sword exist in this world that can pierce the Dragonlord's scales?\""
#define STRING_NPC_NORTHERNSHRINE_WIZARD_1_1                         "\"Bravery is often touted, but rarely tested. It is the latter that must be done here.\""
#define STRING_NPC_NORTHERNSHRINE_WIZARD_1_2                         "\"It is said there is a Silver Harp that beckons to the creatures of the Dragonlord.\""
#define STRING_NPC_NORTHERNSHRINE_WIZARD_1_3                         "\"Give this harp to me and I will reward you with the Staff of Rain!\""
#define STRING_NPC_NORTHERNSHRINE_WIZARD_2_1                         "\"You have brought the harp, excellent! I have waited a long time for one such as you.\""
#define STRING_NPC_NORTHERNSHRINE_WIZARD_2_2                         "\"As promised, I award your bravery with the Staff of Rain!\""
#define STRING_NPC_NORTHERNSHRINE_WIZARD_3                           "\"My brethren dwell in Tantegel castle, and a shrine far to the south, I suggest you seek them out.\""
#define STRING_NPC_SOUTHERNSHRINE_WIZARD_1_1                         "\"Long ago, Erdrick predicted a great evil would return to Alefgard.\""
#define STRING_NPC_SOUTHERNSHRINE_WIZARD_1_2                         "\"He also said a brave hero of his own bloodline would rise to challenge him.\""
#define STRING_NPC_SOUTHERNSHRINE_WIZARD_1_3                         "\"You indeed appear brave, but I cannot help you without proof that you are Erdrick's descendant!\""
#define STRING_NPC_SOUTHERNSHRINE_WIZARD_1_4                         "\"Present to me the Token of Erdrick, and I will show you the way forward.\""
#define STRING_NPC_SOUTHERNSHRINE_WIZARD_2_1                         "\"You have proven yourself as Erdrick's descendant, how wonderful!\""
#define STRING_NPC_SOUTHERNSHRINE_WIZARD_2_2                         "\"Bring to me now the Stone of Sunlight and the Staff of Rain!\""
#define STRING_NPC_SOUTHERNSHRINE_WIZARD_3_1                         "\"It is now time for the sun and the rain to meet...\""
#define STRING_NPC_SOUTHERNSHRINE_WIZARD_3_2                         "\"And lo, the Goddess presents to us the most wondrous spectrum of colors...\""
#define STRING_NPC_SOUTHERNSHRINE_WIZARD_3_3                         "\"I have used all the magic in my being to capture these colors in a vial, please take this Rainbow Drop!\""
#define STRING_NPC_SOUTHERNSHRINE_WIZARD_4                           "\"Descendant of Erdrick, the Goddess smiles upon you!\""
#define STRING_NPC_CHARLOCK_DRAGONLORD_1_1                           "\"Well met, %s! I am the Dragonlord, King of Kings!\""
#define STRING_NPC_CHARLOCK_DRAGONLORD_1_2                           "\"I have been waiting for you, the descendant of Erdrick...\""
#define STRING_NPC_CHARLOCK_DRAGONLORD_1_3                           "\"I acknowledge your strength and your bravery, and as such will offer you a choice.\""
#define STRING_NPC_CHARLOCK_DRAGONLORD_1_4                           "\"Stand beside me, and share my power over Alefgard!\""
#define STRING_NPC_CHARLOCK_DRAGONLORD_1_5                           "\"What say you? Will the great descendant of Erdrick stand with me?\""
#define STRING_NPC_CHARLOCK_DRAGONLORD_2_1                           "\"Hahaha... I knew I sensed the evil within, such bravery and such destructive intent...\""
#define STRING_NPC_CHARLOCK_DRAGONLORD_2_2                           "\"We shall rule this land and see its demise, %s!\""
#define STRING_NPC_CHARLOCK_DRAGONLORD_2_3                           "Thus the hero became the ultimate villain, joining the Dragonlord to destroy Alefgard."
#define STRING_NPC_CHARLOCK_DRAGONLORD_2_4                           "With no true heroes left, the entire kingdom was laid to waste."
#define STRING_NPC_CHARLOCK_DRAGONLORD_3                             "\"Then you are a FOOL!\""
#define STRING_NPC_SWAMPCAVE_PRINCESS_1                              "\"I've waited what seems an eternity for a brave hero to come to my rescue!\""
#define STRING_NPC_SWAMPCAVE_PRINCESS_2                              "\"I am Gwaelin, daughter of King Lorik of Tantegel, I was captured by a dragon and brought here.\""
#define STRING_NPC_SWAMPCAVE_PRINCESS_3                              "\"Please, I must return to my father's side, but I am too weak to stand.\""
#define STRING_NPC_SWAMPCAVE_PRINCESS_4                              "\"%s, will you carry me back to my home?\""
#define STRING_NPC_SWAMPCAVE_PRINCESS_5                              "You embrace Princess Gwaelin."
#define STRING_NPC_SWAMPCAVE_PRINCESS_6                              "\"%s, you are my hero! I am so happy!\""
#define STRING_NPC_SWAMPCAVE_PRINCESS_CURSED_1                       "\"Who goes there? What is this awful feeling in my soul?!\""
#define STRING_NPC_SWAMPCAVE_PRINCESS_CURSED_2                       "\"I can sense the horrible curse that has invaded your aura, it burns my spirit!\""
#define STRING_NPC_SWAMPCAVE_PRINCESS_CURSED_3                       "\"Please just leave me here, death is more welcome than this feeling...\""
#define STRING_NPC_OVERWORLD_PRINCESS                                "\"Please %s, take me home to Tantegel, I must see my father!\""
#define STRING_NPC_OVERWORLD_PRINCESS_NOCURSE_1                      "\"Wait, %s, no! Please do not put on the cursed belt!\""
#define STRING_NPC_OVERWORLD_PRINCESS_NOCURSE_2                      "\"I sense a great evil emanating from it, you must leave it be.\""
#define STRING_NPC_STATICSOLDIER                                     "The soldier is standing at attention, so he cannot speak."
#define STRING_NPC_ENDING_1                                          "Lorik: \"%s, I cannot begin to express my gratitude for your exploits.\""
#define STRING_NPC_ENDING_2                                          "\"I had all but lost faith in the future of Alefgard.\""
#define STRING_NPC_ENDING_3                                          "\"Yet here we stand, the Dragonlord has been defeated and the Sphere of Light is reclaimed!\""
#define STRING_NPC_ENDING_4                                          "\"I never doubted your bravery, but this victory has truly cemented your legacy.\""
#define STRING_NPC_ENDING_5                                          "\"Let the world know that %s truly is Erdrick's descendant!\""
#define STRING_NPC_ENDING_5_1                                        "\"If only my daughter could be present to see it, but I'm afraid she may be lost forever.\""
#define STRING_NPC_ENDING_5_2                                        "\"...\""
#define STRING_NPC_ENDING_6                                          "\"Now there is something I must ask of you.\""
#define STRING_NPC_ENDING_7                                          "\"As the blood of Erdrick flows in your veins, it is your right to rule this land.\""
#define STRING_NPC_ENDING_8                                          "\"Therefore, it is my duty to offer you my crown, and my throne.\""
#define STRING_NPC_ENDING_9                                          "\"%s, will you take my place as King of Alefgard?\""
#define STRING_NPC_ENDING_RESCUED_1                                  "\"Yes, I see...\""
#define STRING_NPC_ENDING_RESCUED_2                                  "\"If you are to rule over a land, it must be a land of your own discovery.\""
#define STRING_NPC_ENDING_RESCUED_3                                  "\"It is said true bravery knows no bounds, and I've witnessed this here today!\""
#define STRING_NPC_ENDING_RESCUED_4                                  "\"So it shall be! %s, I have no doubt you will become King by your own accord.\""
#define STRING_NPC_ENDING_RESCUED_5                                  "\"May the light guide you on your journey!\""
#define STRING_NPC_ENDING_RESCUED_6                                  "Gwaelin: \"%s, wait!\""
#define STRING_NPC_ENDING_RESCUED_7                                  "\"Please, I cannot bear the thought of you leaving!\""
#define STRING_NPC_ENDING_RESCUED_8                                  "\"The sleepless nights I would endure in your absence, never knowing if you will return...\""
#define STRING_NPC_ENDING_RESCUED_9                                  "\"Please, take me with you, so that I may stand by your side, and our love can endure forever.\""
#define STRING_NPC_ENDING_RESCUED_10                                 "\"Let us discover our own kingdom, where we shall rule in peace as King and Queen!\""
#define STRING_NPC_ENDING_RESCUED_11                                 "Lorik: \"What wonderful tidings! My own daughter, the future Queen of a newly discovered land...\""
#define STRING_NPC_ENDING_RESCUED_12                                 "\"And King %s by her side, bringing peace to the world.\""
#define STRING_NPC_ENDING_RESCUED_13                                 "\"All hail the future King and Queen!\""
#define STRING_NPC_ENDING_NOTRESCUED_1                               "\"Ah, I see, you hold faith that my daughter Gwaelin may still be alive...\""
#define STRING_NPC_ENDING_NOTRESCUED_2                               "\"May your unwavering hope never falter, %s!\""
#define STRING_NPC_ENDING_NOTRESCUED_3                               "\"In the wake of the Dragonlord's demise, let us hope she is safe somewhere in this land.\""
#define STRING_NPC_ENDING_NOTRESCUED_4                               "\"May the light guide you on your quest to find my daughter!\""

#define STRING_ENDING_MESSAGE_1                                      "AND THUS, WITH PEACE RESTORED"
#define STRING_ENDING_MESSAGE_2                                      "TO ALEFGARD, %s AND"
#define STRING_ENDING_MESSAGE_3                                      "GWAELIN SAILED TO THE EAST,"
#define STRING_ENDING_MESSAGE_4                                      "SEEKING UNDISCOVERED LANDS."
#define STRING_ENDING_MESSAGE_5                                      "THE ROAD IS LONG,"
#define STRING_ENDING_MESSAGE_6                                      "AND MANY PERILS AWAIT,"
#define STRING_ENDING_MESSAGE_7                                      "BUT COURAGE AND BRAVERY"
#define STRING_ENDING_MESSAGE_8                                      "SHALL ALWAYS PREVAIL."
#define STRING_ENDING_MESSAGE_9                                      "MAY THE LIGHT SHINE UPON YOU!"

#endif // STRINGS_H
