#if !defined( STRINGS_H )
#define STRINGS_H

#define STRING_OVERWORLD_MENU_TITLE    "COMMAND"
#define STRING_OVERWORLD_MENU_TALK     "TALK"
#define STRING_OVERWORLD_MENU_STATUS   "STATUS"
#define STRING_OVERWORLD_MENU_SEARCH   "SEARCH"
#define STRING_OVERWORLD_MENU_SPELL    "SPELL"
#define STRING_OVERWORLD_MENU_ITEM     "ITEM"
#define STRING_OVERWORLD_MENU_DOOR     "DOOR"

#define STRING_OVERWORLD_DIALOG_NOBODY_THERE    "Nobody is there."

#endif // STRINGS_H
